#ifndef SYSTEM_STATE_H
#define SYSTEM_STATE_H

enum SystemMode {
  MODE_SCAN_CARD,
  MODE_ENTER_PASSWORD,
  MODE_ADMIN_MENU,
  MODE_CHANGE_PASSWORD,
  MODE_DEL_CARD,
  MODE_ADD_CARD,
  MODE_VIEW_CARDS,
  MODE_RFID_MENU,
  MODE_FINGERPRINT_MENU,
  MODE_ADD_FINGERPRINT,
  MODE_DELETE_FINGERPRINT,
  MODE_VIEW_FINGERPRINTS
};

#endif
